### ISSUE TITLE
Running package.sh yields DistutilsOptionError

### ISSUE THREAD

**Issue by tmazeika** [infincia/lifx-adapter#3]
I can't say I'm all too familiar with Python packages, but I'm having some issues when running `./package.sh`:

```
Collecting git+https://github.com/mclarkk/lifxlan.git (from -r requirements.txt (line 1))
  Cloning https://github.com/mclarkk/lifxlan.git to /tmp/pip-v2rvai72-build
Collecting bitstring (from lifxlan==1.2.2->-r requirements.txt (line 1))
  Using cached https://www.piwheels.org/simple/bitstring/bitstring-3.1.5-py3-none-any.whl
Collecting netifaces (from lifxlan==1.2.2->-r requirements.txt (line 1))
  Using cached https://www.piwheels.org/simple/netifaces/netifaces-0.10.6-cp35-cp35m-linux_armv7l.whl
Installing collected packages: bitstring, netifaces, lifxlan
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/share/python-wheels/setuptools-33.1.1-py2.py3-none-any.whl/setuptools/command/install.py", line 38, in finalize_options
    orig.install.finalize_options(self)
  File "/usr/lib/python3.5/distutils/command/install.py", line 273, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
```
Just glancing at the error message, I can't say for sure it's an issue with lifx-adapter, but I'm on the latest version of the gateway, have updated system packages, and am using the latest Git version of lifx-adapter.

**Comment by steveatinfincia** [comment]
Ok, I've seen this in practice now, and I know why it happens.

Your pip error has a reference to `armv7`, so I assume you're using Raspbian on a Pi3, right? 

Raspbian is using Debian as their upstream package source. Debian appears to have added a patch in `pip` which silently adds `--user` to every command, and `--user` is incompatible with `--target`, which our `package.sh` script is using.

I haven't seen it until now because I always install the upstream version of `pip`, which doesn't cause this problem.

For now, rather than removing the `python3-pip` package, try *upgrading* first as root, which appears to be safe:

    pip3 install --upgrade pip

Here, that installs the upstream version of `pip` for Python3 to `/usr/local/bin/pip3`, and leaves the rest of the system alone. As long as `/usr/local/bin` appears first in `$PATH`, things should "just work". You can test that by running `which pip3`, it should say `/usr/local/bin/pip3`.

You can *probably* remove the `python3-pip` package if you want to. I don't think anything else should be using it, and both the packaged and upstream versions of `pip` appear to install things in `/usr/local/lib/python3.5/dist-packages` by default.

I don't know if there is a change that could be made to the `package.sh` script to avoid this, as `--target` is being used intentionally.

@mrstegeman what do you think? Is there a better solution?

**Comment by mrstegeman** [comment]
I don't think there's any need to uninstall the system version, but yes, I'd say upgrading to the upstream version of `pip` is the way to go. Alternatively, you could use a `virtualenv` that has a proper `pip` installed.
